platform :ios, '8.0'
use_frameworks!

pod 'AFNetworking', '~>2.6.3'
pod 'M13Checkbox'
pod 'BButton'
pod 'AFXMLDictionarySerializer'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'ADDropDownMenuView', '~> 1.0.0'
pod 'KxMenu'
pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"
pod 'SwiftCharts', '~> 0.3'
pod 'DatePickerCell'
pod 'FBGlowLabel', :git => 'https://github.com/lyokato/FBGlowLabel.git'