platform :ios, '8.0'
use_frameworks!

pod 'AFNetworking', '~>2.6.3'
pod 'M13Checkbox'
pod 'BButton'
pod 'AFXMLDictionarySerializer'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"
