platform :ios, '8.0'

target "HsinchuIOT" do
pod 'AFNetworking', '~>2.6.3'
pod 'M13Checkbox'
pod 'BButton'
pod 'AFXMLDictionarySerializer'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'KxMenu'
pod 'FBGlowLabel', :git => 'https://github.com/lyokato/FBGlowLabel.git'
end
